apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: monitoring
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
        - montech.montech.mylab
  rules:
    - host: montech.montech.mylabhttp:
        paths:
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
          - path: /prometheus
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090
          - path: /billing-api
            pathType: Prefix
            backend:
              service:
                name: billing-api
                port:
                  number: 80
          - path: /billing-metrics
            pathType: Prefix
            backend:
              service:
                name: scaleway-billing-exporter
                port:
                  number: 9091
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
