# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by manual edits!

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "xhci_pci"
    "virtio_blk"
    "virtio_scsi"
    "scsi_mod"
    "usb_storage"
    "usbhid"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "nvidia" "nvidia_uvm" "nvidia_modeset" ];
  boot.extraModulePackages = [ ];

  # Enable NVIDIA
  hardware.enableRedistributFirmware = true;
  hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.stable;

  # File systems
  fileSystems."/" = {
    device = "/dev/sda1";
    fsType = "ext4";
  };

  swapDevices = [ ];

  # Enable Intel WiFi
  networking.wireless.enable = false;

  # Enable NVIDIA GPU hotplug
  services.thermald.enable = true;
}
